[workspace]
members = [
    "crates/backend",
    "crates/frontend",
    "crates/server",
    "crates/tauri",
    "crates/model",
    "crates/crud",
    "crates/crud/migration",
    "crates/crud/entity",
    "crates/update_data",
]
